Repository helios1101/HacktoberFest_19, pull requests merged in 2019-10, with the labels that each got.

#12 Added a new entry with my details
  Task1/img/baedyl.png
  Task1/index.html
Labels: Hacktoberfest, good first issue

#18 Update README.md
  README.md
Labels: Hacktoberfest, documentation

#23 Task1-eken25
  Task1/img/eken25.png
  Task1/index.html
Labels: Hacktoberfest, good first issue

#27 Task-3-hello_world.dart
  Task3/dart/hello_world.dart
Labels: Hacktoberfest, enhancement

#41 Task1-anchal7299
  Task1/img/aanchal.jpe
  Task1/img/anchal7299.jpg
  Task1/index.html
Labels: Hacktoberfest, good first issue

#13 updated spelling
  Task3/README.md
Labels: Hacktoberfest, good first issue

#11 Update README.md
  README.md
Labels: Hacktoberfest, good first issue

#28 Task1-BradleyPJ
  Task1/img/bradleypj.jpg
  Task1/index.html
Labels: Hacktoberfest
